-- MVP-02 — Customer and Task Creation
--
-- Purely additive: new enums, new tables, new indexes, new foreign keys
-- (all onDelete RESTRICT except the Task-owned child tables, which are
-- CASCADE because they have no independent existence), two new CHECK
-- constraints, and one new sequence. No existing table, column, row, or
-- constraint is altered, dropped, or truncated. Existing Users, Roles,
-- UserRoleAssignments, AuthSessions, RefreshTokenRecords are untouched.
--
-- Generated by `prisma migrate diff --from-migrations ... --to-schema-datamodel
-- ... --shadow-database-url <ephemeral local shadow DB>` (offline — no
-- connection to the real Dispatch database was used to author this file),
-- then hand-reviewed and extended with the CHECK constraints and sequence
-- below, which schema.prisma cannot express directly.

-- CreateEnum
CREATE TYPE "delivery_task_status" AS ENUM ('DRAFT', 'WAITING_PREPARATION', 'PREPARING', 'READY_FOR_DISPATCH', 'ASSIGNED', 'IN_TRANSIT', 'AT_DESTINATION', 'WAITING_NEXT_ATTEMPT', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "destination_source" AS ENUM ('MASTER', 'FREE_TEXT');

-- CreateEnum
CREATE TYPE "free_text_fallback_reason" AS ENUM ('NO_SUITABLE_MASTER', 'AD_HOC_DESTINATION');

-- CreateTable
CREATE TABLE "customers" (
    "id" UUID NOT NULL,
    "code" VARCHAR(64),
    "name" VARCHAR(255) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_destinations" (
    "id" UUID NOT NULL,
    "customer_id" UUID NOT NULL,
    "code" VARCHAR(64),
    "destination_name" VARCHAR(255) NOT NULL,
    "address" TEXT NOT NULL,
    "contact_name" VARCHAR(255),
    "contact_phone" VARCHAR(32),
    "delivery_instructions" TEXT,
    "location_reference" VARCHAR(255),
    "access_notes" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "customer_destinations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_master_searches" (
    "id" UUID NOT NULL,
    "searched_by_user_id" UUID NOT NULL,
    "normalized_query" VARCHAR(120) NOT NULL,
    "matched_customer_destination_ids" TEXT[],
    "result_count" INTEGER NOT NULL,
    "searched_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "customer_master_searches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "delivery_tasks" (
    "id" UUID NOT NULL,
    "task_number" VARCHAR(32) NOT NULL,
    "status" "delivery_task_status" NOT NULL DEFAULT 'DRAFT',
    "planned_delivery_date" DATE,
    "created_by_user_id" UUID NOT NULL,
    "updated_by_user_id" UUID NOT NULL,
    "submitted_at" TIMESTAMPTZ(6),
    "destination_source" "destination_source" NOT NULL,
    "customer_id" UUID,
    "customer_destination_id" UUID,
    "customer_search_id" UUID NOT NULL,
    "free_text_fallback_reason" "free_text_fallback_reason",
    "customer_name" VARCHAR(255) NOT NULL,
    "destination_name" VARCHAR(255) NOT NULL,
    "address" TEXT NOT NULL,
    "contact_name" VARCHAR(255),
    "contact_phone" VARCHAR(32),
    "delivery_instructions" TEXT,
    "location_reference" VARCHAR(255),
    "access_notes" TEXT,
    "customer_code_snapshot" VARCHAR(64),
    "destination_code_snapshot" VARCHAR(64),
    "snapshot_created_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "delivery_tasks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "delivery_task_items" (
    "id" UUID NOT NULL,
    "task_id" UUID NOT NULL,
    "line_number" INTEGER NOT NULL,
    "description" VARCHAR(500) NOT NULL,
    "planned_quantity" DECIMAL(18,3) NOT NULL,
    "unit" VARCHAR(32) NOT NULL,
    "notes" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "delivery_task_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_references" (
    "id" UUID NOT NULL,
    "task_id" UUID NOT NULL,
    "reference_type" VARCHAR(64) NOT NULL,
    "reference_value" VARCHAR(128) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_references_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "task_events" (
    "id" UUID NOT NULL,
    "task_id" UUID NOT NULL,
    "event_type" VARCHAR(64) NOT NULL,
    "previous_status" "delivery_task_status",
    "new_status" "delivery_task_status" NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "task_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "customers_name_idx" ON "customers"("name");

-- CreateIndex
CREATE UNIQUE INDEX "customers_code_key" ON "customers"("code");

-- CreateIndex
CREATE INDEX "customer_destinations_customer_id_idx" ON "customer_destinations"("customer_id");

-- CreateIndex
CREATE INDEX "customer_destinations_destination_name_idx" ON "customer_destinations"("destination_name");

-- CreateIndex
CREATE INDEX "customer_master_searches_searched_by_user_id_idx" ON "customer_master_searches"("searched_by_user_id");

-- CreateIndex
CREATE INDEX "customer_master_searches_expires_at_idx" ON "customer_master_searches"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_tasks_task_number_key" ON "delivery_tasks"("task_number");

-- CreateIndex
CREATE INDEX "delivery_tasks_status_idx" ON "delivery_tasks"("status");

-- CreateIndex
CREATE INDEX "delivery_tasks_planned_delivery_date_idx" ON "delivery_tasks"("planned_delivery_date");

-- CreateIndex
CREATE INDEX "delivery_tasks_created_by_user_id_idx" ON "delivery_tasks"("created_by_user_id");

-- CreateIndex
CREATE INDEX "delivery_tasks_customer_search_id_idx" ON "delivery_tasks"("customer_search_id");

-- CreateIndex
CREATE INDEX "delivery_task_items_task_id_idx" ON "delivery_task_items"("task_id");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_task_items_task_id_line_number_key" ON "delivery_task_items"("task_id", "line_number");

-- CreateIndex
CREATE INDEX "task_references_task_id_idx" ON "task_references"("task_id");

-- CreateIndex
CREATE UNIQUE INDEX "task_references_task_id_reference_type_reference_value_key" ON "task_references"("task_id", "reference_type", "reference_value");

-- CreateIndex
CREATE INDEX "task_events_task_id_idx" ON "task_events"("task_id");

-- AddForeignKey
ALTER TABLE "customer_destinations" ADD CONSTRAINT "customer_destinations_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_master_searches" ADD CONSTRAINT "customer_master_searches_searched_by_user_id_fkey" FOREIGN KEY ("searched_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_customer_destination_id_fkey" FOREIGN KEY ("customer_destination_id") REFERENCES "customer_destinations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_customer_search_id_fkey" FOREIGN KEY ("customer_search_id") REFERENCES "customer_master_searches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_task_items" ADD CONSTRAINT "delivery_task_items_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "delivery_tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_references" ADD CONSTRAINT "task_references_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "delivery_tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_events" ADD CONSTRAINT "task_events_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "delivery_tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_events" ADD CONSTRAINT "task_events_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CreateSequence
-- Backs the collision-safe, human-readable Task number (BR-TASK-001:
-- "traceable and stable for the Task's lifetime"). Task-number *format* is
-- not specified anywhere in Dispatch Knowledge Topics 01-07/11 — this is a
-- technical decision, not a resolution of any BDR. A Postgres sequence's
-- nextval() is atomic and gap-tolerant, so concurrent Task creation can
-- never produce a duplicate value without relying on counting existing
-- rows. formatDeliveryTaskNumber() (packages/domain) renders it as
-- "DSP-########".
CREATE SEQUENCE IF NOT EXISTS "dispatch_task_number_seq" START WITH 1 INCREMENT BY 1;

-- CreateCheckConstraint
-- Destination-source consistency (BR-TASK-003 / VR-TASK-001a), enforced at
-- the database level in addition to the application layer: MASTER requires
-- both a Customer and Customer Destination reference and forbids a
-- fallback reason; FREE_TEXT forbids both Master references and requires a
-- fallback reason. No row may satisfy neither branch.
ALTER TABLE "delivery_tasks" ADD CONSTRAINT "delivery_tasks_destination_source_consistency_check" CHECK (
  ("destination_source" = 'MASTER' AND "customer_id" IS NOT NULL AND "customer_destination_id" IS NOT NULL AND "free_text_fallback_reason" IS NULL)
  OR
  ("destination_source" = 'FREE_TEXT' AND "customer_id" IS NULL AND "customer_destination_id" IS NULL AND "free_text_fallback_reason" IS NOT NULL)
);

-- CreateCheckConstraint
-- Defense-in-depth for BR-TASK-003/VR-TASK-001a's positive-quantity rule,
-- in addition to application-layer validation.
ALTER TABLE "delivery_task_items" ADD CONSTRAINT "delivery_task_items_planned_quantity_positive_check" CHECK ("planned_quantity" > 0);
